### ISSUE TITLE
能否多加几个倒计时的备用字段

### ISSUE THREAD

**Issue by FlawlessChen** [rxrw/daily_morning#116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rxrw** [comment]
好主意，提个 pr從我的iPhone傳送chenqingfei ***@***.***>於2022年8月29日 09:55寫道：﻿
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Describe the solution you'd like
A clear and concise description of what you want to happen.
Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
Additional context
Add any other context or screenshots about the feature request here.

**Comment by rxrw** [comment]
搞定了
