### ISSUE TITLE
关于电脑未关机但不自动发送的问题

### ISSUE THREAD

**Issue by enson0329** [rxrw/daily_morning#129]
提问前翻看一下有没有历史有人提过的问题！

**描述一下存在的问题**
请在此清楚明白地说明出现的问题，不要给我说 Exit code 1，把最后几行都复制粘贴过来。

**如何产生的**
你的变量如何设置，尤其是城市、两个日期的值和模板是什么样子的

**截图**
将你微信公众平台测试号的模板内容和 Github 的报错截图粘贴过来

**其他说明**
你好博主，程序在github里手动运行正常，但是第二天没有自动发送怎么办？延迟通常是多久？等了两个多小时也没收到只好手动发送

**Comment by peiyangL** [comment]
你是在自己电脑上运行的还是在Github actions运行的？

**Comment by enson0329** [comment]
> 你是在自己电脑上运行的还是在Github actions运行的？

github actions运行的

**Comment by peiyangL** [comment]
> 

那和你电脑是否关机没有关系。应该是延迟问题。

**Comment by enson0329** [comment]
> 那和你电脑是否关机没有关系。应该是延迟问题。

可是都十点多了他都没发正常吗，延迟这么久吗。感谢大佬解惑！

**Comment by peiyangL** [comment]
不太清楚。但根据很多人的反馈，github actions的稳定性确实欠佳。

可以考虑自己在本机运行：https://github.com/rxrw/daily_morning#%E4%BB%A3%E7%A0%81%E4%BD%BF%E7%94%A8

**Comment by JionghaoSong** [comment]
有一个两个小时延迟很正常的
我之前顶的北京时间8点，9.36才推过来的

**Comment by enson0329** [comment]
> 
我不知道为啥现在是下午两点准时发，很奇怪啊

**Comment by enson0329** [comment]
> 有一个两个小时延迟很正常的 我之前顶的北京时间8点，9.36才推过来的

我不知道为啥现在是下午两点准时发，很奇怪，怎么改时间啊在github actions 运行的

**Comment by enson0329** [comment]
> Workflow file中，cron: '0 0 * * *`，是 UTC 时间的零点，北京时间的八点。 具体可以看文档 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "rxrw/daily_morning" ***@***.***&gt;; Date:&nbsp;Wed, Aug 31, 2022 08:00 PM ***@***.***&gt;; ***@***.******@***.***&gt;; Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129) 有一个两个小时延迟很正常的 我之前顶的北京时间8点，9.36才推过来的 我不知道为啥现在是下午两点准时发，很奇怪，怎么改时间啊在github actions 运行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我的work file中corn: ' 0 0 * * * '没有改过，但是发送时间就是北京时间的14：00，这咋回事，应该怎么改啊，多谢帮助

**Comment by enson0329** [comment]
> 试试&nbsp;' 01 0 * * * ' 避开拥挤时间吧，最好用自己呃服务器
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "rxrw/daily_morning" ***@***.***&gt;; Date:&nbsp;Wed, Aug 31, 2022 08:15 PM ***@***.***&gt;; ***@***.******@***.***&gt;; Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129) Workflow file中，cron: '0 0 * * `，是 UTC 时间的零点，北京时间的八点。 具体可以看文档 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows … ------------------&nbsp;Original&nbsp;------------------ From: "rxrw/daily_morning" @.&gt;; Date:&nbsp;Wed, Aug 31, 2022 08:00 PM @.&gt;; @.@.&gt;; Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129) 有一个两个小时延迟很正常的 我之前顶的北京时间8点，9.36才推过来的 我不知道为啥现在是下午两点准时发，很奇怪，怎么改时间啊在github actions 运行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.**&gt; 我的work file中corn: ' 0 0 * * * '没有改过，但是发送时间就是北京时间的14：00，这咋回事，应该怎么改啊，多谢帮助 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

麻烦问一下继续用cron可以吗，&nbsp不是空格吗？学的比较浅，麻烦解惑

**Comment by JionghaoSong** [comment]
on:
&nbsp; schedule:
&nbsp; - cron:&nbsp; '01 0 * * *'
&nbsp; workflow_dispatch:



但是都不准的，免费的东西，不用强求了




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "rxrw/daily_morning"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Aug 31, 2022 08:29 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129)





  
试试&nbsp;' 01 0 * * * ' 避开拥挤时间吧，最好用自己呃服务器
 …
 ------------------&nbsp;Original&nbsp;------------------ From: "rxrw/daily_morning" @.&gt;; Date:&nbsp;Wed, Aug 31, 2022 08:15 PM @.&gt;; @.@.&gt;; Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129) Workflow file中，cron: '0 0 * * `，是 UTC 时间的零点，北京时间的八点。 具体可以看文档 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows … ------------------&nbsp;Original&nbsp;------------------ From: "rxrw/daily_morning" @.&gt;; Date:&nbsp;Wed, Aug 31, 2022 08:00 PM @.&gt;; @.@.&gt;; Subject:&nbsp;Re: [rxrw/daily_morning] 关于电脑未关机但不自动发送的问题 (Issue #129) 有一个两个小时延迟很正常的 我之前顶的北京时间8点，9.36才推过来的 我不知道为啥现在是下午两点准时发，很奇怪，怎么改时间啊在github actions 运行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 我的work file中corn: ' 0 0 * * * '没有改过，但是发送时间就是北京时间的14：00，这咋回事，应该怎么改啊，多谢帮助 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.*&gt;
  
麻烦问一下继续用cron可以吗，&amp;nbsp不是空格吗？学的比较浅，麻烦解惑
